name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/myapp/base
          push: true
          tags: yourdockerhubusername/myapp:latest

      - name: Update image tag in deployment manifest
        run: |
          sed -i 's|image: yourdockerhubusername/myapp:.*|image: yourdockerhubusername/myapp:latest|' clusters/fluxcd-poc-aks/apps/myapp-deployment.yaml

      - name: Commit updated manifest
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add clusters/fluxcd-poc-aks/apps/myapp-deployment.yaml
          git commit -m "Update image tag to latest"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
